application: dtsimpleblog
version: react
runtime: python27
api_version: 1

threadsafe: true

builtins:
- deferred: on
- remote_api: on

inbound_services:
- warmup

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest

handlers:
- url: /(robots\.txt)
  static_files: static/\1
  upload: static/(.*)
  login: required

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /login
  script: routes.application
  login: admin

- url: /dist
  static_dir: static/dist





- url: /login
  script: routes.application

- url: /api/v1/get_single_post
  script: routes.application

- url: /test
  script: routes.application

- url: /make_post
  script: routes.application

- url: /create_posts
  login: admin
  script: routes.application

- url: /is_logged_in
  login: admin
  script: routes.application

- url: /api/v1/your_posts
  login: admin
  script: routes.application

- url: /update_post
  login: admin
  script: routes.application


skip_files:
- ^coverage/.*
- ^coverage_html_report/.*
- ^migration/.*
- ^monitor/.*
- ^export/.*
- ^pa/.*
- ^scripts/.*
- ^snapdeploy.yaml
- ^images/readme.md
- ^local/.*
- ^tests/.*
- ^simtests/.*
- ^webapp/.*
- ^.git/.*
- ^.idea/.*
- ^.*~
- ^.*\.py[co]
- ^.*\.po
- ^.*\.pot
- ^.*\.egg-info
- ^\.DS_Store.*
- ^(.*/)?.*static/node_modules/.*
